Update mdbook-mermaid tag in deploy.yml (#23)
* Update mdbook-mermaid tag in deploy.yml

Signed-off-by: Daniel Adams <70986246+msub2@users.noreply.github.com>

* Update README.md

Updated mdbook-mermaid version number

---------

Signed-off-by: Daniel Adams <70986246+msub2@users.noreply.github.com>

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -39,9 +39,9 @@ jobs:
         run: |
           tag=$(curl 'https://api.github.com/repos/badboy/mdbook-mermaid/releases/latest' | jq -r '.tag_name')
           case "$tag" in
-            (v0.13.*) ;;
+            (v0.14.*) ;;
             (*)
-              >&2 echo 'Error: latest version of mdbook-mermaid is no longer ^0.13'
+              >&2 echo 'Error: latest version of mdbook-mermaid is no longer ^0.14'
               exit 1
               ;;
           esac
