CI: check that latest mdbook and mdbook-mermaid are not breaking

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -26,11 +26,25 @@ jobs:
       - name: Install latest mdbook
         run: |
           tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
+          case "$tag" in
+            (v0.4.*) ;;
+            (*)
+              >&2 echo 'Error: latest version of mdbook is no longer ^0.4'
+              exit 1
+              ;;
+          esac
           url="https://github.com/rust-lang/mdbook/releases/download/$tag/mdbook-$tag-x86_64-unknown-linux-gnu.tar.gz"
           curl -sSL "$url" | tar -xz --directory=./opt/mdbook
       - name: Install latest mdbook-mermaid
         run: |
           tag=$(curl 'https://api.github.com/repos/badboy/mdbook-mermaid/releases/latest' | jq -r '.tag_name')
+          case "$tag" in
+            (v0.13.*) ;;
+            (*)
+              >&2 echo 'Error: latest version of mdbook-mermaid is no longer ^0.13'
+              exit 1
+              ;;
+          esac
           url="https://github.com/badboy/mdbook-mermaid/releases/download/$tag/mdbook-mermaid-$tag-x86_64-unknown-linux-gnu.tar.gz"
           curl -sSL "$url" | tar -xz --directory=./opt/mdbook-mermaid
       - name: Build book
